### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by meimei-kr** [meimei-kr/idea-space-trip#136]
## 各種情報
サービス名：IDEA SPACE TRIP
サービスURL：https://www.idea-space-trip.net/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 会員登録・ログイン機能
- [ ] ゲストログイン機能
- [x] アイデア出しセッション機能
- [x] アイデアメモ一覧閲覧機能
- [x] アイデアメモ詳細閲覧機能
- [x] アイデアメモ編集機能
- [x] アイデアメモ削除機能
- [ ] Xシェア機能

## READMEレビュー時から変更した機能
【削除・保留】
- ゲストログイン機能
　Googleログイン機能で簡単にログインしていただけるため、ゲストログイン機能は削除しました。
- Xシェア機能
　実装するか検討中のため、MVPリリースでは対応しませんでした。

## サービスイメージがわかるようなスクリーンショット等
※管理画面は作成しておりません。
### トップページ
[![Image from Gyazo](https://i.gyazo.com/ef84a0b7d9ca5a03c86d9397144d341c.jpg)](https://gyazo.com/ef84a0b7d9ca5a03c86d9397144d341c)
### アプリ説明
[![Image from Gyazo](https://i.gyazo.com/4960cdc671fd9cf52748b8116a653fd1.png)](https://gyazo.com/4960cdc671fd9cf52748b8116a653fd1)
### 機能説明
[![Image from Gyazo](https://i.gyazo.com/b726b7e9e6a4bad78b0b1d2868a38c12.png)](https://gyazo.com/b726b7e9e6a4bad78b0b1d2868a38c12)
### 登録・ログイン画面
[![Image from Gyazo](https://i.gyazo.com/285d028e4790ed4d90264e45a16e685e.png)](https://gyazo.com/285d028e4790ed4d90264e45a16e685e)
### モード選択画面
[![Image from Gyazo](https://i.gyazo.com/700d74713ed90cb296d97b01949e7647.png)](https://gyazo.com/700d74713ed90cb296d97b01949e7647)
### アイデア出しのテーマ有無選択画面
[![Image from Gyazo](https://i.gyazo.com/a8a334baee6921ece08f1569e9f9fcda.png)](https://gyazo.com/a8a334baee6921ece08f1569e9f9fcda)
### テーマが決まっている場合の入力画面
[![Image from Gyazo](https://i.gyazo.com/1aa7493c1cf899e52889552cfc0fe558.png)](https://gyazo.com/1aa7493c1cf899e52889552cfc0fe558)
### テーマが決まっていない場合のカテゴリー選択画面
[![Image from Gyazo](https://i.gyazo.com/c93091fbfcd194dc9c09b4aefdd467bb.png)](https://gyazo.com/c93091fbfcd194dc9c09b4aefdd467bb)
### テーマが決まっていない場合の質問選択と回答入力画面
[![Image from Gyazo](https://i.gyazo.com/68ce0fcdc50a0fd4d48a977f3d795c95.png)](https://gyazo.com/68ce0fcdc50a0fd4d48a977f3d795c95)
[![Image from Gyazo](https://i.gyazo.com/489c4a05af6ac7412013ae3652a60706.png)](https://gyazo.com/489c4a05af6ac7412013ae3652a60706)
### アイデア出し画面
[![Image from Gyazo](https://i.gyazo.com/221b6e26472cb802cb193fa2a2f4bff4.png)](https://gyazo.com/221b6e26472cb802cb193fa2a2f4bff4)
[![Image from Gyazo](https://i.gyazo.com/f3796e681f0723307055685edaa76f71.png)](https://gyazo.com/f3796e681f0723307055685edaa76f71)
### アイデア出し終了画面
[![Image from Gyazo](https://i.gyazo.com/839066c6245e7246e07da2f6dfacf97f.png)](https://gyazo.com/839066c6245e7246e07da2f6dfacf97f)
[![Image from Gyazo](https://i.gyazo.com/fb82874fb67b4d9626896dc09c1661a6.png)](https://gyazo.com/fb82874fb67b4d9626896dc09c1661a6)
### アイデアメモ一覧画面
[![Image from Gyazo](https://i.gyazo.com/518b3c6af35ad6e7505411c0d6c8816c.png)](https://gyazo.com/518b3c6af35ad6e7505411c0d6c8816c)
### アイデアメモ詳細画面
[![Image from Gyazo](https://i.gyazo.com/10b90bfd1fc33b6bbc6f8cb1c2924287.png)](https://gyazo.com/10b90bfd1fc33b6bbc6f8cb1c2924287)
### アイデアメモ編集画面
[![Image from Gyazo](https://i.gyazo.com/7ccc4b2d695808f6ce1c74543c45a46e.png)](https://gyazo.com/7ccc4b2d695808f6ce1c74543c45a46e)

**Comment by kenchasonakai** [comment]
LGTMです！

**Comment by meimei-kr** [comment]
@kenchasonakai さん
お忙しい中ご確認いただきありがとうございました。
issueクローズいたします。
