### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by meimei-kr** [meimei-kr/idea-space-trip#41]
### 実装予定の機能
- 会員登録・ログイン・ゲストログイン機能
- アイデア出しセッション機能
- アイデアメモ一覧閲覧機能
- アイデアメモ詳細閲覧機能
- アイデアメモ編集機能
- アイデアメモ削除機能

### 必要なページ
- トップページ
- モード選択画面
- テーマ有無確認画面
- 【テーマありの場合】テーマ入力画面
- 【テーマなしの場合】テーマカテゴリ選択画面
- 【テーマなしの場合】テーマ案生成画面
- アイデア出し画面
- アイデア出し終了画面
- アイデアストックメモ一覧画面
- アイデアストックメモ詳細画面
- アイデアストックメモ編集画面

**Comment by busitora** [comment]
Projectsから看板・isssue・ストーリーポイントを確認しようとしましたが、確認できませんでした。対象カリキュラムに参考のリンクがあったかと思うのでご確認とご対応をお願いいたします。

https://school.runteq.jp/v3/curriculums/graduate_examination/chapters/4

**Comment by meimei-kr** [comment]
申し訳ございません。
visibilityがprivateになっておりました。
publicに変更いたしましたので、再度ご確認のほどお願い致します。

**Comment by beppumasaki** [comment]
LGTMです！
